[general]
import = [
    "themes/tokyonight_moon.toml"
]

[window]
opacity = 0.9
padding = { x = 5, y = 5 }

[font]
size = 10.0
normal = { family = "JetBrainsMono NF", style = "SemiBold" }

[colors.primary]
background = '#111111'
